name: End-to-End Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install make
        run: apt-get install -y make
      - name: Run e2e tests
        # We don't want to kill the build if the tests fail (yet)
        run: make test_e2e_run_docker || exit 0
