name: Lighthouse PWA Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deploy to succeed
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.ref }}
          check-name: 'Main CI'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Run Lighthouse check against Fleek deployment
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ steps.deploy.outputs.deployUrl }}
          configPath: '.github/lighthouse/lighthouserc.yml'
          uploadArtifacts: true
          temporaryPublicStorage: true
