name: Lighthouse PWA Test

on:
  workflow_run:
    workflows: ['Main CI']
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse check against Fleek deployment
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            ${{ steps.deploy.outputs.deployUrl }}
          configPath: '.github/lighthouse/lighthouserc.yml'
          uploadArtifacts: true
          temporaryPublicStorage: true
