name: Lighthouse PWA Test

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  build-for-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout front end code.
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Build UI for production
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
        env:
          CI: false
      - name: Run Lighthouse PWA check against local production build
        uses: treosh/lighthouse-ci-action@v9
        with:
          # no urls needed, since it uses local folder to scan .html files
          # budgetPath: '.github/lighthouse/budget.json' # uncommment if we want custom performance budgets
          configPath: '.github/lighthouse/lighthouserc-static-dist-dir.yml'
          uploadArtifacts: true # save results as github action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: 'guFcs6FrptZPOXChQK8zjRjbF6n9RHQElkMTaj-xlW4' # ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: '278d83a0-6ffd-4fff-b9e7-2f76b590dfe9' # ${{ secrets.NETLIFY_SITE_ID }}
      - name: Wait for Netlify preview deployment of this git branch
        uses: JakePartusch/wait-for-netlify-action@v1.3
        id: waitFor60
        with:
          site_name: "olympus-frontend"
      - name: Run Lighthouse PWA check against Netlify PR Preview
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ steps.get-netlify-url.outputs.url }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: '.github/lighthouse/lighthouserc-netlify-preview.yml'
