name: Lighthouse PWA Test

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  Run-Lighthouse-PWA-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout front end code.
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Build UI for production
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
        env:
          CI: false
      - name: Run Lighthouse PWA check against local production build
        uses: treosh/lighthouse-ci-action@v9
        with:
          # no urls needed, since it uses local folder to scan .html files
          # budgetPath: '.github/lighthouse/budget.json' # uncommment if we want custom performance budgets
          configPath: '.github/lighthouse/lighthouserc-static-dist-dir.yml'
          uploadArtifacts: true # save results as github action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Deploy to Netlify
        id: deploy-to-netlify
        uses: jsmrcaga/action-netlify-deploy@v1.7.2
        env:
          CI: false
        with:
          # update auth token and site id before merge to main:
          NETLIFY_AUTH_TOKEN: 'guFcs6FrptZPOXChQK8zjRjbF6n9RHQElkMTaj-xlW4' # ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: '278d83a0-6ffd-4fff-b9e7-2f76b590dfe9' # ${{ secrets.NETLIFY_SITE_ID }}
          node_version: "16"
      - name: Run Lighthouse PWA check against Netlify PR Preview
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls:
            ${{ steps.deploy-to-netlify.outputs.NETLIFY_PREVIEW_URL }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: '.github/lighthouse/lighthouserc-netlify-preview.yml'
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Check out the preview
      - if: steps.find-comment.outputs.comment-id != ''
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.find-comment.outputs.comment-id }}
            })
      - name: Create or update comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.number}}
          body: |
            [Check out the preview for this PR here](${{ steps.deploy-to-netlify.outputs.NETLIFY_PREVIEW_URL }})
            ${{ steps.deploy-to-netlify.outputs.NETLIFY_PREVIEW_URL }}
          reactions: '+1'
      - name: Status check
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: ${{ steps.deploy-to-netlify.outputs.NETLIFY_PREVIEW_URL }}
