name: Main CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  deploy:
#    needs: [test]
    runs-on: ubuntu-latest
    # run Fleek deployment via this github action only on pull requests - for now
    if: ${{ github.ref != 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy site to Fleek
        id: deploy
        uses: fleekhq/action-deploy@master
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - name: Get the output url
        run: echo "Deploy url is ${{ steps.deploy.outputs.deployUrl }}"
